[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools"]

[phases.install]
cmds = ["cd faq-backend && python -m pip install --upgrade pip", "cd faq-backend && python -m pip install -r requirements.txt"]

[start]
cmd = "cd faq-backend && python railway_start.py"

[variables]
PYTHONPATH = "faq-backend"
