[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd faq-backend && python -m ensurepip --upgrade", "cd faq-backend && python -m pip install -r requirements.txt"]

[start]
cmd = "cd faq-backend && python railway_start.py"
